### ISSUE TITLE
RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by Daxide** [FinucaneLab/pops#1]
I completed step 1. At step 2, after I run  I run
python pops.feature_selection.py --features PoPS.features.txt.gz --gene_results trial--out trial

I get the following warning:

local/lib/python2.7/site-packages/statsmodels/base/model.py:1294: RuntimeWarning: invalid value encountered in divide
  return self.params / self.bse

**Comment by kyleyxw** [comment]
Same issue occurred. I was wondering the versions of the Python dependencies

**Comment by ruthchia** [comment]
Hi Elle, I encountered the same error message.
I used python/3.5. What do you think is causing this error message?

```[+] Loading python 3.5  ... 
/usr/local/Anaconda/envs/py3.5/lib/python3.5/site-packages/statsmodels/base/model.py:1100: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
```

Btw, loved the talk you gave at ASHG 2020 hence I am testing your software out! Would love to make it work 👍

**Comment by bnj50** [comment]
Hi Elle I am also getting same error:
bash-4.2$ pops.feature_selection.py --features PoPS.features.txt.gz --gene_results kenmagma --out ken-step2
 
/usr/local/python/3.7.1/lib/python3.7/site-packages/statsmodels/base/model.py:1362: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse

**Comment by julirsch** [comment]
Nathan -- can you help them with this issue?

**Comment by nchengbroad** [comment]
Hi yes! As I understand it this is expected behavior. I think some features are constant and the way we compute their p-values leads to a divide by zero problem. However, you should still get the correct output even with this runtime error. In a future version we'll handle this more elegantly.

**Comment by bnj50** [comment]
Hi...so after last line:
/usr/local/python/3.7.1/lib/python3.7/site-packages/statsmodels/base/model.py:1362: RuntimeWarning: invalid value encountered in true_divide
return self.params / self.bse

the program doesn't do anything in my case.

**Comment by nchengbroad** [comment]
Does the program terminate with a particular error message? I don't believe Python terminates on runtime warnings by default.

If the script appears to be hanging, it could just be that it's still running. The feature selection step does take a while.

**Comment by bnj50** [comment]
thank you, you are correct. it generate the output. 
 if i add another question, in step 3 is there a way that program evaluate all chromsomes at once or we have to do this one chr at a time? also how to interpret the scores  (most positive / most negative) and what is the range?

**Comment by nchengbroad** [comment]
Unfortunately the program only works one chromosome at a time. The output is the predicted MAGMA one-sided z-score for each gene (using the gene features as X), so the high scoring genes are the genes of interest. The output is essentially unbounded. Our recommendation is to look at the top scoring gene in each locus of interest.

**Comment by ruthchia** [comment]
Hi, thanks for he replies. Following up on the last reply re: looking at top scoring gene in each locus, would you just say you would look at genes at the smaller and largest  1% or would you set an arbitrary score cut off to look at? eg: > 1.5 and < 1.5 ?

**Comment by julirsch** [comment]
To echo what @nchengbroad mentioned, I probably wouldn't set any threshold if you're doing this for GWAS follow-up -- we we usually just rank in a locus. If a gene has a particularly high PoPS score (top 1% of all genes), then maybe we're a little more confident, but we haven't made any hard and fast rules. Sometimes a locus will have generally low scores, but one gene will have a higher (although still low) score, and it will be clear that this gene is the likely causal GWAS gene.

**Comment by bnj50** [comment]
Thank you all…I plan to first calculate score per chr, then combine all chr and then look into top 1% ( or do I need to do this in each chr separately?)

Best
bahram

**Comment by julirsch** [comment]
Hi @bnj50 -- sorry if I wasn't clear as this seems like the opposite of what we suggest!

Definitely calculate the score per chromosome and combine. Then, define what your loci are (usually between 200kb-3Mb) using the GWAS signals (you do this separately from the software). Within each locus, we then rank genes by score, regardless of how high or low it is and take the top ranked gene as the prioritized gene. Many of the validations in the preprint are done using this "top ranked gene" (per locus).
