### ISSUE TITLE
Interpretation of scores

### ISSUE THREAD

**Issue by tanmoy63** [FinucaneLab/pops#4]
Hi, How to interpret positive and negative scores for genes? I mean if I have five genes with score (-2,-1,0,1,2), which are the two top scores, ie, (1,2) or (-2,2)? Thanks for your help.

**Comment by julirsch** [comment]
Hi @tanmoy63,

We currently suggest taking the highest scoring gene in each GWAS locus. You could further filter this set to only include genes in top 10% of PoP scores across all genes. Negative scores generally mean low evidence -- this is the predicted MAGMA z-score!!

Best,
Jacob

**Comment by ConnorBarnhill** [comment]
Hello,

Does this not mean that genes with a negative MAGMA Z-score have a protective effect?
